# Generated by Django 4.2.2 on 2023-06-13 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='static/portfolio')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]