# Generated by Django 4.2.2 on 2023-06-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profile.breed'),
        ),
    ]
