# Generated by Django 4.2.2 on 2023-06-14 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_alter_pet_breed'),
        ('portfolio', '0002_portfolio_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='breed',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='profile.breed'),
        ),
    ]
