# Generated by Django 4.2.2 on 2023-06-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_alter_pet_breed'),
        ('portfolio', '0003_alter_portfolio_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profile.breed'),
        ),
    ]
