# Generated by Django 4.2.2 on 2023-07-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_pet_user'),
        ('portfolio', '0004_alter_portfolio_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio', to='profile.breed'),
        ),
    ]
