# Generated by Django 4.2.2 on 2023-06-13 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Тип витрат')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Назва придбаного товару')),
                ('cost', models.IntegerField(verbose_name='Вартість')),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Коментар')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.type', verbose_name='Тип витрат')),
            ],
        ),
    ]
