# Generated by Django 4.2.7 on 2024-03-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('expenses', '0004_alter_expenses_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='groomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grooming_expenses', to='profiles.groomer'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_type', to='expenses.type', verbose_name='Тип витрат'),
        ),
    ]
