# Generated by Django 4.1.7 on 2023-02-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(db_index=True, max_length=255, verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Породи',
                'verbose_name_plural': 'Порода',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255, verbose_name='Послуга')),
                ('cost', models.IntegerField(verbose_name='Вартість')),
                ('time', models.CharField(max_length=255, verbose_name='Час виконання')),
                ('content', models.TextField(blank=True, max_length=255, null=True, verbose_name='Опис')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Тип витрат')),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='static/portfolio')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groom.breed')),
            ],
        ),
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва придбаного товару')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість')),
                ('data', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=255, verbose_name='Коментар')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groom.type', verbose_name='Тип витрат')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('city', models.CharField(choices=[('KIEV', 'Київ'), ('MYRGOROD', 'Миргород')], max_length=10, verbose_name='Місто')),
                ('pet_name', models.CharField(max_length=255, verbose_name='Кличка тварини')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('photo', models.FileField(upload_to='static/groom', verbose_name='Фото')),
                ('comments', models.TextField(blank=True, max_length=255, null=True, verbose_name='Коментар')),
                ('status', models.CharField(choices=[('WAITING', 'Очікує'), ('ACCEPTED', 'Прийнято'), ('PROCESSING', 'В обробці'), ('DECLINED', 'Відхилено')], default='WAITING', max_length=10, verbose_name='Статус заявки')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groom.breed', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Заявки',
                'ordering': ['data'],
            },
        ),
    ]
