# Generated by Django 4.1.7 on 2023-02-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['data'], 'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявка'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Витрати', 'verbose_name_plural': 'Витрати'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Портфоліо', 'verbose_name_plural': 'Портфоліо'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Ціни', 'verbose_name_plural': 'Ціна'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип витрат', 'verbose_name_plural': 'Типи витрат'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='photo',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='', upload_to='static/portfolio'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Номер телефону'),
        ),
    ]
