# Generated by Django 4.1.7 on 2023-03-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groom', '0003_alter_client_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='cost',
            new_name='cost_kiev',
        ),
        migrations.RemoveField(
            model_name='price',
            name='service',
        ),
        migrations.AddField(
            model_name='price',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='groom.breed', verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='price',
            name='cost_murgorod',
            field=models.IntegerField(default=1, verbose_name='Вартість'),
            preserve_default=False,
        ),
    ]
