# Generated by Django 4.1.7 on 2023-03-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groom', '0004_rename_cost_price_cost_kiev_remove_price_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cost_kiev',
            field=models.IntegerField(verbose_name='Вартість Київ'),
        ),
        migrations.AlterField(
            model_name='price',
            name='cost_murgorod',
            field=models.IntegerField(verbose_name='Вартість Миргород'),
        ),
    ]
