# Generated by Django 4.1.7 on 2023-03-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groom', '0005_alter_price_cost_kiev_alter_price_cost_murgorod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groom.breed', verbose_name='Порода'),
        ),
    ]
