# Generated by Django 4.2.7 on 2024-03-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='pets.breed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='особливості'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/pet_photo'),
        ),
    ]
