# Generated by Django 4.2.2 on 2023-06-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('cost_kiev', models.IntegerField(verbose_name='Вартість Київ')),
                ('cost_murgorod', models.IntegerField(verbose_name='Вартість Миргород')),
                ('service_time', models.CharField(max_length=255, verbose_name='Час виконання')),
                ('content', models.TextField(blank=True, max_length=255, null=True, verbose_name='Опис')),
                ('breed', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='profile.breed', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Ціни',
                'verbose_name_plural': 'Ціна',
            },
        ),
    ]