# Generated by Django 4.2.2 on 2023-06-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='cost_kiev',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Вартість Київ'),
        ),
        migrations.AlterField(
            model_name='services',
            name='cost_murgorod',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Вартість Миргород'),
        ),
    ]
