# Generated by Django 4.2.2 on 2023-06-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_cost_kiev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='cost_kiev',
            field=models.IntegerField(verbose_name='Вартість Київ'),
        ),
        migrations.AlterField(
            model_name='services',
            name='cost_murgorod',
            field=models.IntegerField(verbose_name='Вартість Миргород'),
        ),
    ]
