# Generated by Django 4.2.2 on 2023-07-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_pet_user'),
        ('services', '0003_alter_services_cost_kiev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='breed',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='profile.breed', verbose_name='Порода'),
        ),
    ]
