# Generated by Django 4.2.2 on 2023-07-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_reviews_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='author',
        ),
    ]
