# Generated by Django 4.2.2 on 2023-07-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_user_reviews_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='author',
            new_name='user',
        ),
    ]
